name: Publish Python Package

on:
  release:
    types: [published]  # Trigger this workflow when a new release is published

permissions:
  contents: read  # Required to fetch repository content
  id-token: write  # Required for GitHub Actions to authenticate with PyPI

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository code
      - name: Check out code
        uses: actions/checkout@v3

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      # Install dependencies and build tools
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip build

      # Build the package
      - name: Build the package
        run: python -m build

      # Publish the package to PyPI
      - name: Publish to PyPI
        env:
          TWINE_USERNAME: __token__  # PyPI username for token-based auth
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}  # PyPI API token
        run: |
          python -m pip install --upgrade twine
          twine upload --repository pypi dist/*
